### ISSUE TITLE
前端登录时发送API的地址错误

### ISSUE THREAD

**Issue by baka-9** [wangzmgit/alnitak#18]
![1](https://github.com/wangzmgit/alnitak/assets/122795463/17a6fe6f-d3ff-435f-8a4f-e95ac0360dfd)
![2](https://github.com/wangzmgit/alnitak/assets/122795463/cb946859-4be2-446f-a31e-ad2841a659a2)

默认docker部署下的前端发送请求的API地址为客户本地的http://localhost:9000
而非server_ip:9000

**Comment by baka-9** [comment]
哎？是我的问题吗，我修改成服务器IP后还是一样登录不了，点进去API的网址也显示404

**Comment by wangzmgit** [comment]
> 哎？是我的问题吗，我修改成服务器IP后还是一样登录不了，点进去API的网址也显示404

可能会有跨域问题，如果跨域了就要在后端配置一下跨域。

**Comment by baka-9** [comment]
> > 哎？是我的问题吗，我修改成服务器IP后还是一样登录不了，点进去API的网址也显示404
> 
> 可能会有跨域问题，如果跨域了就要在后端配置一下跨域。

我知道了，大佬你的默认后端配置文件里的跨域链接是你视频里的端口（

但是我全部都改完之后根据教程里的账号密码登录还是显示“获取用户信息失败”

而且本地localhost:9000地址的问题还是一样

**Comment by wangzmgit** [comment]
默认配置写错了，导致数据库没有默认数据
