### ISSUE TITLE
网站文档中的接口文档缺少了资源

### ISSUE THREAD

**Issue by fuuuzzy** [wangzmgit/alnitak#43]
访问视频资源相关页面显示404，大佬帮忙补充下
![Snipaste_2024-07-10_22-53-05.png](https://s2.loli.net/2024/07/10/vqRViWDAB8usdft.png)

**Comment by wangzmgit** [comment]
我这边是正常的

**Comment by fuuuzzy** [comment]
ok 我看这边也显示正常了
