### ISSUE TITLE
wplayer next问题请教。播放器元素显示异常，求大佬指教哪里写的出错了

### ISSUE THREAD

**Issue by z5qdi59** [wangzmgit/alnitak#68]
仿照case：https://github.com/wangzmgit/alnitak/blob/master/web/web-client/src/components/video-player/index.vue

本人的代码code如下：
[DanmakuVideo copy.vue.zip](https://github.com/user-attachments/files/18165524/DanmakuVideo.copy.vue.zip)

但是实际播放效果为：
![2024-12-17 204009](https://github.com/user-attachments/assets/4ae1e13b-4f8c-4411-9533-abfe8c263ea7)
视频播放链接异常（wplayer旧版本的就没问题）
![2024-12-17 204430](https://github.com/user-attachments/assets/5fb32461-9da7-4cbc-bd2c-31f528c2808e)
弹幕发送也失效（wplayer旧版本的也没问题）
![2024-12-17 204435](https://github.com/user-attachments/assets/80909d43-618b-49b1-81fa-557eb80d6e4c)
请大佬麻烦有空看看是哪里出的问题呢？
相应项目结构引用为：
![2024-12-17 204222](https://github.com/user-attachments/assets/a2627e41-4f7d-4548-98ad-98bfeac54f38)
![2024-12-17 204317](https://github.com/user-attachments/assets/cb0dc481-06fe-4af4-8e77-4a0197653355)

**Comment by wangzmgit** [comment]
首先是视频资源存在跨域问题。其次，播放器在这个项目中播放的是Hls不能播放mp4。弹幕发送组件与播放器无关，为自定义组件，依赖element ui。可以参考dplayer相关教程，播放器大部分配置与dplayer一致

**Comment by z5qdi59** [comment]
多谢指点

**Comment by z5qdi59** [comment]
基本都解决了，多谢大佬给小白指明方向。

**Comment by z5qdi59** [comment]
略微赞助，多谢指点
